#!/usr/bin/pythone
def raise_exception_msg(message=""):
    raise NameError("{:s}".format(message))
